language: java
script: mvn install
env:
  global:
  - secure: g0A9usPhe/Tj0lnuCwUHgA88fsJ0eU1sgBCUUEUXDSE9wqyHs8ossEagRXOv3RFA+mULCXHuiSyD0CCkvfSfvL9zYzZO3XOcNiMy8GWZahUtYJph256bvw8D5/Y+HJTD8ppvPYjptKs6RyQSfQw796XIMUWHQQhUaKX6a2jho40=
  - secure: aV7iNqT38xPCa0PaDP9daA0ykB08j6tK+hVp5aEiQLmZZqCZXnSzPNESZDvLq7IqT5vbynNGMti96gi0jVEnltFY+5ZTSXEmSQycYNzoBOG2zRrb3mk5rYBd3cu/vvA8J3JvJEb+oRuIt8rCL27Qa/oL/+qdvL+vlPnHPK0v+zo=
